### ISSUE TITLE
the sip version problem

### ISSUE THREAD

**Issue by a358003542** [wbsoft/python-poppler-qt5#1]
I can not import the popplerqt5 , and use the python3.4 compile it , the sip use the version 4.16.6 . what should i do ?

    >>> import popplerqt5
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    RuntimeError: the sip module implements API v11.0 but the popplerqt5 module requires API v11.1

**Comment by wbsoft** [comment]
Can you import PyQt5.QtCore?

**Comment by a358003542** [comment]
Yes ， I can .

**Comment by wbsoft** [comment]
Thanks. And can you import sip?
```pytyhon
>>> import sip
```

**Comment by a358003542** [comment]
Sorry, i go out for a period , cannot test it right now. 发自网易邮箱大师 On 2015-03-09 21:15 , Wilbert Berendsen Wrote: Thanks. And can you import sip? >>> import sip

**Comment by anthonyfok** [comment]
Hello @a358003542,

When you have time, could you please test again if `import popplerqt5` and `import sip` work for you?  Also, if you don't mind me asking, what OS are you using now?  (e.g. Ubuntu Linux?  Which version?)

Many thanks!

**Comment by a358003542** [comment]
now i can import popplerqt5 properly . please close this issue. but  last time i am on the ubuntu14.04 32, this time i am on the ubuntu14.04 64 . sorry that for take it so long time and i can not reappear it .

```
wanze@wanze-ubuntu64:~/桌面$ python3
Python 3.4.0 (default, Jun 19 2015, 14:20:21) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyQt5.QtCore
>>> import sip
>>> import popplerqt5
>>> 
```

**Comment by a358003542** [comment]
BTW , maybe this helpful:

```
>>> from sip import SIP_VERSION_STR
>>> print(SIP_VERSION_STR)
4.15.5
>>> from PyQt5.Qt import PYQT_VERSION_STR
>>> print(PYQT_VERSION_STR)
5.2.1
>>> from PyQt5.QtCore import QT_VERSION_STR
>>> print(QT_VERSION_STR)
5.2.1

```

**Comment by anthonyfok** [comment]
@a358003542, Thank you very much for your helpful feedback!

I was curious of your test result because I am in the process of packaging `python-poppler-qt5` for Debian (See https://bugs.debian.org/798087), so it is a relief to know that you no longer experience the issue.  Hope the new `python3-poppler-qt5` package will reach Ubuntu in the not-to-distant future.  :wink:

On closer look, I think the error message you saw was the key:

> `RuntimeError: the sip module implements API v11.0 but the popplerqt5 module requires API v11.1`

My wild guess is that you might have used a newer version of SIP (self-compiled?) to build python-poppler-qt5 locally, but when you tried to `import popplerqt5`, it has instead found an older SIP runtime library that comes with the `python3-sip` package on Ubuntu.

For your information, the very latest `python3-sip` on Debian sid/unstable provides an even newer API, symbolized by the virtual packages "sip-py3api-XX.Y", as shown in the excerpt from `apt-cache show python3-sip`:

```
Package: python3-sip
Source: sip4
Version: 4.16.9+dfsg-1
Installed-Size: 268
Maintainer: Debian Python Modules Team <python-modules-team@lists.alioth.debian.org>
Architecture: amd64
Provides: sip-py3api-11.0, sip-py3api-11.1, sip-py3api-11.2
```
